# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_api:
    resource: "@SyliusAdminApiBundle/Resources/config/routing.yml"
    prefix: /api

# sylius_shop:
#     resource: "@SyliusShopBundle/Resources/config/routing.yml"
#     prefix: /{_locale}
#     requirements:
#         _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

# sylius_shop_default_locale:
#     path: /
#     methods: [GET]
#     defaults:
#         _controller: sylius.controller.shop.locale_switch:switchAction

app_a-propos:
    path: /a-propos
    methods: [GET]
    defaults:
        _controller: AppBundle:Default:aPropos

app_charte-de-confidentialite:
    path: /charte-de-confidentialite
    methods: [GET]
    defaults:
        _controller: AppBundle:Default:charteDeConfidentialite

app_conditions-generales-de-vente:
    path: /conditions-generales-de-vente
    methods: [GET]
    defaults:
        _controller: AppBundle:Default:conditionsGeneralesDeVente

app_livraison-&-expedition:
    path: /livraison-&-expedition
    methods: [GET]
    defaults:
        _controller: AppBundle:Default:LivraisonExpedition

app_actualite:
    path: /actualites
    methods: [GET]
    defaults:
        _controller: AppBundle:Default:actualite

app_admin:
    resource: 'routing/admin.yml'
    prefix: /admin
